services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: focu_sqlserver
    environment:
      - SA_PASSWORD=${SA_PASSWORD} # set in .env file
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
        
volumes:
  sqlserver_data: